
import json
from pprint import pprint

with open(r'C:\Users\Vicky\AppData\Roaming\.minecraft\saves\Demo_World\stats\8792cc36-8230-8cff-e745-c0e32290caa2.json') as f:
    x = f.read()
    x = json.loads(x)

# pprint(x['stats']['minecraft:picked_up'])
pprint(x['stats'])


'''
{'minecraft:crafted': {'minecraft:crafting_table': 1,
                       'minecraft:oak_planks': 12,
                       'minecraft:stick': 4,
                       'minecraft:wooden_sword': 1},
 'minecraft:custom': {'minecraft:crouch_one_cm': 695,
                      'minecraft:damage_dealt': 1279,
                      'minecraft:damage_taken': 1150,
                      'minecraft:deaths': 4,
                      'minecraft:drop': 2,
                      'minecraft:fall_one_cm': 5192,
                      'minecraft:fly_one_cm': 3563,
                      'minecraft:interact_with_crafting_table': 1,
                      'minecraft:jump': 226,
                      'minecraft:mob_kills': 11,
                      'minecraft:play_time': 27911,
                      'minecraft:sneak_time': 540,
                      'minecraft:sprint_one_cm': 58926,
                      'minecraft:swim_one_cm': 9353,
                      'minecraft:time_since_death': 4177,
                      'minecraft:time_since_rest': 4206,
                      'minecraft:total_world_time': 64321,
                      'minecraft:walk_on_water_one_cm': 18095,
                      'minecraft:walk_one_cm': 108051,
                      'minecraft:walk_under_water_one_cm': 11570},
 'minecraft:dropped': {'minecraft:egg': 2},
 'minecraft:killed': {'minecraft:chicken': 3,
                      'minecraft:cow': 2,
                      'minecraft:drowned': 1,
                      'minecraft:enderman': 1,
                      'minecraft:pig': 2,
                      'minecraft:sheep': 2},
 'minecraft:killed_by': {'minecraft:drowned': 4},
 'minecraft:mined': {'minecraft:chest': 1,
                     'minecraft:crafting_table': 1,
                     'minecraft:dirt': 46,
                     'minecraft:grass': 2,
                     'minecraft:grass_block': 24,
                     'minecraft:gravel': 3,
                     'minecraft:lilac': 10,
                     'minecraft:oak_leaves': 8,
                     'minecraft:oak_log': 3,
                     'minecraft:sand': 23,
                     'minecraft:spruce_leaves': 1,
                     'minecraft:torch': 4},
 'minecraft:picked_up': {'minecraft:apple': 1,
                         'minecraft:beef': 2,
                         'minecraft:bread': 2,
                         'minecraft:chest': 1,
                         'minecraft:chicken': 3,
                         'minecraft:copper_ingot': 1,
                         'minecraft:crafting_table': 1,
                         'minecraft:dirt': 83,
                         'minecraft:egg': 6,
                         'minecraft:feather': 4,
                         'minecraft:grass_block': 1,
                         'minecraft:gravel': 3,
                         'minecraft:leather': 4,
                         'minecraft:lilac': 10,
                         'minecraft:mangrove_log': 3,
                         'minecraft:mutton': 3,
                         'minecraft:oak_log': 6,
                         'minecraft:porkchop': 3,
                         'minecraft:sand': 47,
                         'minecraft:spruce_log': 3,
                         'minecraft:torch': 4,
                         'minecraft:wheat_seeds': 1,
                         'minecraft:white_wool': 3,
                         'minecraft:wooden_axe': 1,
                         'minecraft:wooden_pickaxe': 1},
 'minecraft:used': {'minecraft:crafting_table': 1,
                    'minecraft:dirt': 48,
                    'minecraft:grass_block': 1,
                    'minecraft:mutton': 2,
                    'minecraft:sand': 23,
                    'minecraft:wooden_sword': 28}}
 '''
