
import json
from pprint import pprint

with open(r'C:\Users\Vicky\AppData\Roaming\.minecraft\saves\Demo_World\stats\8792cc36-8230-8cff-e745-c0e32290caa2.json') as f:
    x = f.read()
    x = json.loads(x)

# pprint(x['stats']['minecraft:picked_up'])
pprint(x['stats'])


'''
{'minecraft:crafted': {'minecraft:crafting_table': 1,
                       'minecraft:oak_planks': 12,
                       'minecraft:stick': 4,
                       'minecraft:wooden_sword': 1},
 'minecraft:custom': {'minecraft:crouch_one_cm': 695,
                      'minecraft:damage_dealt': 1080,
                      'minecraft:damage_taken': 1070,
                      'minecraft:deaths': 3,
                      'minecraft:fall_one_cm': 4654,
                      'minecraft:fly_one_cm': 3509,
                      'minecraft:interact_with_crafting_table': 1,
                      'minecraft:jump': 181,
                      'minecraft:mob_kills': 10,
                      'minecraft:play_time': 21569,
                      'minecraft:sneak_time': 505,
                      'minecraft:sprint_one_cm': 53156,
                      'minecraft:swim_one_cm': 3524,
                      'minecraft:time_since_death': 3442,
                      'minecraft:time_since_rest': 3482,
                      'minecraft:total_world_time': 52628,
                      'minecraft:walk_on_water_one_cm': 11128,
                      'minecraft:walk_one_cm': 91439,
                      'minecraft:walk_under_water_one_cm': 7223},
 'minecraft:killed': {'minecraft:chicken': 3,
                      'minecraft:cow': 2,
                      'minecraft:enderman': 1,
                      'minecraft:pig': 2,
                      'minecraft:sheep': 2},
 'minecraft:killed_by': {'minecraft:drowned': 3},
 'minecraft:mined': {'minecraft:chest': 1,
                     'minecraft:crafting_table': 1,
                     'minecraft:dirt': 35,
                     'minecraft:grass': 2,
                     'minecraft:grass_block': 15,
                     'minecraft:gravel': 3,
                     'minecraft:lilac': 10,
                     'minecraft:oak_leaves': 8,
                     'minecraft:oak_log': 3,
                     'minecraft:sand': 20,
                     'minecraft:spruce_leaves': 1,
                     'minecraft:torch': 4},
 'minecraft:picked_up': {'minecraft:apple': 1,
                         'minecraft:beef': 2,
                         'minecraft:bread': 2,
                         'minecraft:chest': 1,
                         'minecraft:chicken': 3,
                         'minecraft:crafting_table': 1,
                         'minecraft:dirt': 49,
                         'minecraft:egg': 2,
                         'minecraft:feather': 4,
                         'minecraft:grass_block': 1,
                         'minecraft:gravel': 3,
                         'minecraft:leather': 4,
                         'minecraft:lilac': 10,
                         'minecraft:mangrove_log': 3,
                         'minecraft:mutton': 3,
                         'minecraft:oak_log': 6,
                         'minecraft:porkchop': 3,
                         'minecraft:sand': 28,
                         'minecraft:spruce_log': 3,
                         'minecraft:torch': 4,
                         'minecraft:wheat_seeds': 1,
                         'minecraft:white_wool': 3,
                         'minecraft:wooden_axe': 1,
                         'minecraft:wooden_pickaxe': 1},
 'minecraft:used': {'minecraft:crafting_table': 1,
                    'minecraft:dirt': 21,
                    'minecraft:grass_block': 1,
                    'minecraft:mutton': 2,
                    'minecraft:sand': 12,
                    'minecraft:wooden_sword': 28}}
 '''
